export_fbx:
  hide: false
  steps:
    export_fbx:
      label: "ExportFBX"
      index: 20
      commands:
        export_fbx:
          path: "silex_houdini.commands.export_fbx.ExportFBX"
          ask_user: true
