export_fbx:
  hide: false
  steps:
    export_fbx:
      label: "ExportFBX"
      index: 20
      commands:
        export_fbx:
          path: "silex_houdini.commands.export_fbx.ExportFBX"
          ask_user: true
          parameters:
            outdir: !command-output "setup:build_output_path:temp_directory"
            outfilename: !command-output "setup:build_output_path:file_name"

    move:
      label: "Move"
      index: 60
      commands:
        move:
          label: "Move"
          path: "silex_client.commands.move_file.MoveFile"
          parameters:
            file_path: !command-output "export:export_fbx"
            dst_dir: !command-output "setup:build_output_path:directory"
            from_temp: true
