ass:
  steps:
    check_references:
      label: "Check references"
      index: 30
      commands:
        manual_mode:
          label: "Set update mode to manual"
          path: "silex_houdini.commands.set_update_mode.SetUpdateMode"
          parameters:
            mode: "Manual"
        get_references:
          label: "Get referenced files"
          path: "silex_houdini.commands.get_references.GetReferences"
          parameters:
            filters:
              - ".obj"
              - ".fbx"
              - ".bgeo"
              - ".bgeo.sc"
              - ".hda"
              - ".hdanc"
              - ".abc"
        conform_references:
          label: "Conform references found"
          path: "silex_client.commands.iterate_action.IterateAction"
          parameters:
            values: 
              value: !command-output "check_references:get_references:file_paths"
              hide: true
            actions:
              - "conform"
            categories:
              - "action"
            parameter: "setup:get_conform_output:file_paths"
            label_key: "file_paths"
            output: "setup:append_conform_actions"

    conform_references:
      label: "Check references"
      index: 40
      commands:
        repath_attributes:
          label: "Repath attributes"
          path: "silex_houdini.commands.set_references.SetReferences"
          tooltip: "Set the new path on the attributes"
          parameters:
            attributes: 
              value: !command-output "check_references:get_references:attributes"
              hide: true
            values: !command-output "check_references:conform_references"

    export:
      label: "Export"
      index: 50
      commands:
        export_ass:
          label: "Export in Ass"
          path: "silex_houdini.commands.export_ass.ExportAss"
          ask_user: true
          parameters:
            file_dir: 
              value: !command-output "setup:build_output_path:temp_directory"
              hide: true
            file_name: 
              value: !command-output "setup:build_output_path:file_name"
              hide: true
    move:
      label: "Move"
      index: 60
      commands:
        move:
          label: "Move exported files to publish folder"
          path: "silex_client.commands.move.Move"
          parameters:
            src: 
              value: !command-output "export:export_ass"
              hide: true
            dst: 
              value: !command-output "setup:build_output_path:directory"
              hide: true
        remove:
          label: "Remove temp directory"
          path: "silex_client.commands.remove.Remove"
          parameters:
            file_path: 
              value: !command-output "setup:build_output_path:temp_directory"
              hide: true
