bgeo:
  steps:
    export:
      label: "Export"
      index: 50
      commands:
        export_bgeo:
          label: "Export in BGEO"
          path: "silex_houdini.commands.export_geometry.ExportGeometry"
          ask_user: true
          parameters:
            file_dir: 
              value: !command-output "setup:build_output_path:temp_directory"
              hide: true
            file_name: 
              value: !command-output "setup:build_output_path:file_name"
              hide: true
            output_type: "bgeo"

    move:
      label: "Move"
      index: 60
      commands:
        move:
          label: "Move exported files to publish folder"
          path: "silex_client.commands.move.Move"
          parameters:
            src: 
              value: !command-output "export:export_bgeo"
              hide: true
            dst: 
              value: !command-output "setup:build_output_path:directory"
              hide: true
        remove:
          label: "Remove temp directory"
          path: "silex_client.commands.remove.Remove"
          parameters:
            file_path: 
              value: !command-output "setup:build_output_path:temp_directory"
              hide: true
