obj:
  steps:
    export:
      label: "Export"
      index: 50
      commands:
        export_obj:
          label: "Export in OBJ"
          path: "silex_houdini.commands.export_obj.ExportOBJ"
          parameters:
            file_dir: 
              value: !command-output "setup:build_output_path:temp_directory"
              hide: true
            file_name: 
              value: !command-output "setup:build_output_path:file_name"
              hide: true

    move:
      label: "Move"
      index: 60
      commands:
        move:
          label: "Move exported files to publish folder"
          path: "silex_client.commands.move.Move"
          parameters:
            src: 
              value: !command-output "export:export_obj"
              hide: true
            dst: 
              value: !command-output "setup:build_output_path:directory"
              hide: true
        remove:
          label: "Remove temp directory"
          path: "silex_client.commands.remove.Remove"
          parameters:
            file_path: 
              value: !command-output "setup:build_output_path:temp_directory"
              hide: true
