vdb:
  steps:
    export:
      label: "Export"
      index: 50
      commands:
        export_vdb:
          label: "Export in VDB"
          path: "silex_houdini.commands.export_geometry.ExportGeometry"
          ask_user: true
          parameters:
            file_dir: !command-output "setup:build_output_path:temp_directory"
            file_name: !command-output "setup:build_output_path:file_name"
            output_type: "vdb"

    move:
      label: "Move"
      index: 60
      commands:
        move:
          label: "Move exported files to publish folder"
          path: "silex_client.commands.move.Move"
          parameters:
            src: !command-output "export:export_vdb"
            dst: !command-output "setup:build_output_path:directory"
        remove:
          label: "Remove temp directory"
          path: "silex_client.commands.remove.Remove"
          parameters:
            file_path: !command-output "setup:build_output_path:temp_directory"

