hip:
  steps:
    input:
      index: 10
      hide: True
      commands:
        input:
          path: "silex_client.commands.pass.Pass"

    conform_references:
      label: "Conform Houdini scene's references"
      index: 20
      commands:
        open:
          label: "Open scene to conform"
          path: "silex_houdini.commands.open.Open"
          parameters:
            file_path: !command-output "input:input:file_paths"
            save: True
        get_references:
          label: "Get referenced files"
          path: "silex_houdini.commands.get_references.GetReferences"
        conform_references:
          label: "Conform references found"
          path: "silex_client.commands.iterate_action.IterateAction"
          parameters:
            values: !command-output "conform_references:get_references:file_paths"
            actions: 
              - "conform"
            categories:
              - "action"
            parameter: "setup:get_conform_output:file_paths"
            label_key: "file_paths"
            output: "setup:append_conform_actions"

    conform_scene:
      label: "Conform Houdini scene"
      index: 30
      commands:
        build_output_path:
          label: "Build output path"
          path: "silex_client.commands.build_output_path.BuildOutputPath"
          tooltip: "Build the complete output path"
          parameters:
            name: !command-output "input:input:file_paths"
            use_current_context: false
            create_temp_dir: false
            frame_set:
              value: 0
              hide: true
            output_type:
              value: "hip"
              hide: true
          ask_user: true
        repath_attributes:
          label: "Repath attributes"
          path: "silex_houdini.commands.set_references.SetReferences"
          tooltip: "Set the new path on the attributes"
          parameters:
            attributes: !command-output "conform_references:get_references:attributes"
            values: !command-output "conform_references:conform_references"
            indexes: !command-output "conform_references:get_references:indexes"
        clean_hdas:
          label: "Remove unused HDA definitions"
          path: "silex_houdini.commands.clear_hdas.ClearHDAs"
          tooltip: "Uninstall the HDA definitions that where repathed"
        save:
          label: "Save the maya scene to the right location"
          path: "silex_houdini.commands.save.Save"
          parameters:
            file_path: !command-output "conform_scene:build_output_path:full_path"
        open:
          label: "Open back the original scene"
          path: "silex_houdini.commands.open.Open"
          parameters:
            file_path: !command-output "conform_references:open:old_path"
            save: False

    output:
      index: 40
      hide: true
      commands:
        output:
          path: "silex_client.commands.pass.Pass"
          parameters:
            input: !command-output "conform_scene:save:new_path"
